schema_version = "1.0.0"

id = "align_view_to_selection"
version = "1.1.0"
name = "Align View to Selection"
tagline = "Align the viewport to a best-fit plane from selected vertices"
maintainer = "tatsu020"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
